### ISSUE TITLE
ReSharper 9.1 support

### ISSUE THREAD

**Issue by splintor** [JetBrains/resharper-presentation-assistant#10]
Currently with [ReSharper 9.1](http://blog.jetbrains.com/dotnet/2015/04/08/meet-resharper-9-1-resharper-c-1-0-dottrace-6-1-and-more-resharper-ultimate-product-updates/), Presentation Assistant is not listed in the Extension Manager, because 9.1 SDK was changed and extension [needs](http://blog.jetbrains.com/dotnet/2015/04/08/meet-resharper-9-1-resharper-c-1-0-dottrace-6-1-and-more-resharper-ultimate-product-updates/#comment-399866) to be [ported](http://blog.jetbrains.com/dotnet/2015/04/08/meet-resharper-9-1-resharper-c-1-0-dottrace-6-1-and-more-resharper-ultimate-product-updates/#comment-399886). Any expected date?

**Comment by AnnaMilovaJB** [comment]
Could you add ReSharper 9.2 support, please?

**Comment by ChrisMissal** [comment]
:+1:

**Comment by citizenmatt** [comment]
Yep, once the 9.2 EAP SDK is available. Hopefully with the next EAP release.

**Comment by citizenmatt** [comment]
Actually, I'm going to close this issue, as the 9.1 version has been released, and I forgot to close it then. The issue to track for 9.2 support is #11.
