### ISSUE TITLE
Activated state of Presentation doesn't persist when restarting VS

### ISSUE THREAD

**Issue by llewelynrex** [JetBrains/resharper-presentation-assistant#12]
Presentation Assistant functions very well when I've activated it, but as soon as I shut down Visual Studio and open Visual Studio up again, the Presentation Assistant checkbox in the Tools menu is disabled again.

Is there a way to persist the setting?

I'm running on Visual Studio 2013 Professional on a Windows 7 Professional 64bit OS.

Kind regards,
Llewelyn Rex

**Comment by babarqb** [comment]
Same here in vs 2015 remain problem  Activated state of Presentation doesn't persist when restarting VS any soluiton

**Comment by citizenmatt** [comment]
It wasn't designed to be persisted across restarts, as it's intended as a presentation aide. Is this a feature you'd like to see? Would be easy enough to implement. To satisfy my curiosity, why do you want it to persist?

**Comment by llewelynrex** [comment]
Hi there,
honestly, I'm lazy or I forget to activate it. 
It's not just useful for presenting; it could also be a learning tool for the developer. Say I don't know a particular keyboard shortcut within Visual Studio: when the Presentation Assistant is active, it shows me what the keyboard shortcut would be when I click on the function. It's useful to learn new shortcuts for functions that you regularly use, but don't necessarily know the keyboard shortcuts for. 
It does go beyond the purpose and scope of a presentation assistant though.
I'd say it's a nice-to-have.

Regards Llewelyn Rex
Date: Mon, 14 Sep 2015 05:35:53 -0700

**Comment by Necrowizard** [comment]
Bump. I'd like this as well
