### ISSUE TITLE
Persist enabled state Issue Still after update

### ISSUE THREAD

**Issue by babarqb** [JetBrains/resharper-presentation-assistant#14]
I just updated plugin into 2.3.1 butt Persist enabled state doest not work still.  May b i dont known  how to enable it  please help.

**Comment by citizenmatt** [comment]
It should just turn itself on, the first time you run it. Nothing happens? The check mark is unchecked?

**Comment by babarqb** [comment]
Thanks for you quick response. I double check it  but after restart it does not work. As you said it is started by self  but it is not work until i go to enable it by manually

**Comment by babarqb** [comment]
One more thing i just update it. Can i uninstall it and then reinstall  or it is ok with update.

**Comment by citizenmatt** [comment]
Should be fine to update, as long as you restart Visual Studio.

**Comment by babarqb** [comment]
I already restarted Vs 2015 many time but problem still there.  Persist enabled state  does not work. But Plugins work very well  when enable it. I uninstall and reinstall it again and told you result.

**Comment by babarqb** [comment]
It is confirmed that  just updated Plugins is not working until we uninstall it and reinstall it. Thanks It is working straight way after reinstalling it.  Thanks  Issued resolved.

**Comment by citizenmatt** [comment]
An update should have worked, but glad to see it's working now.

**Comment by babarqb** [comment]
Thanks for you time to b with me until i resolve my issue. So nice of you. Take care

**Comment by babarqb** [comment]
Thanks for you time to b with me until i resolve my issue. So nice of you. Take care
