### ISSUE TITLE
A setting to not to show hints if an action was invoked via keyboard shortcut

### ISSUE THREAD

**Issue by Zarium** [JetBrains/resharper-presentation-assistant#21]
I understand this is probably the opposite of what this plugin is trying to achieve, but I think this this popup thingy can be very useful for memorizing keyboard shortcuts. 

Basically the idea is to make it configurable so it would only show hints if an action was invoked using any method other than keyboard shortcut (if that is at all possible in VS/Resharper API). 
Right now it displays them for every action and it is too distracting if your goal is memorizing frequently used shortcuts.

I know that VS shows the shortcuts next to the menu items, but this popup is far more readable and intuitive.

**Comment by citizenmatt** [comment]
Unfortunately, it's not possible - there's no way of knowing what caused the action, whether it was mouse, menu, keyboard, toolbar or even programmatically. All we get is that the action was invoked. This is the same for both VS commands and ReSharper commands. Sorry.
