### ISSUE TITLE
Presentation-Assistant extension crashes

### ISSUE THREAD

**Issue by AFM56** [JetBrains/resharper-presentation-assistant#24]
Using Visual Studio 2017 Community -- 26430.6 release, with Presentation-Assistant 2.7 crashes randomly... with only a message to check Visual Studio Activity log for more details.  Below  is the activity log info.  (Same problem after uninstalling all other R:Sharper Extensions (via Resharper Extension mgr).

System.NullReferenceException: Object reference not set to an instance of an object. at Microsoft.VisualStudio.Editor.Implementation.CommandFilterPerfTracker.RecordDelaySource(Object slowestComponent) at Microsoft.VisualStudio.Editor.Implementation.CommandFilterPerfTracker.TrackTypingDelay(TrackCommandsType commandType) at Microsoft.VisualStudio.Editor.Implementation.CommandFilterPerfTracker.StopTracking(TrackCommandsType typingCommandType) at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam) at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args) at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args) at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)

**Comment by matkoch** [comment]
@AFM56 are you sure this is caused by presentation assistant? The stacktrace looks like it's rather not the problem.
