### ISSUE TITLE
Focus moves to main VS window when command invoked

### ISSUE THREAD

**Issue by spikeyTheBest** [JetBrains/resharper-presentation-assistant#25]
If I make a command in a separate window, for example Ctrl+C, the focus moves to the main VS window where the presentation assistant displays the command. 

This can be a problem, can there be a setting to turn this off? So that it only displays the command if it is executed in the main window.

**Comment by matkoch** [comment]
With separate window, you mean something like a tool window?

Currently presentation assistant doesn't come with any options dialog, and I think we would like to keep that :)

**Comment by spikeyTheBest** [comment]
Okay, maybe it is more of a bug than something that should be an option. It only seems to happen when the smaller window isn't maximised. For example if I've set up my VS windows like this:

![image](https://user-images.githubusercontent.com/29863888/27795084-991a241a-5ffc-11e7-9aa1-337e09e1e03f.png)

and I press Ctrl+C, or Ctrl+. or any keyboard shortcut, it always switches focus to the main window where the presentation assistant displays:

![image](https://user-images.githubusercontent.com/29863888/27795128-cadb687e-5ffc-11e7-8a7d-190834f97cb6.png)

So I can't do shortcuts in windows that aren't maximized.

**Comment by matkoch** [comment]
This is indeed not a good behavior. I will see if we can fix that.

**Comment by matkoch** [comment]
Hi @spikeyTheBest,

I've created a PR (#26). Let's wait for a review from @citizenmatt.

**Comment by matkoch** [comment]
@spikeyTheBest as soon as ReSharper vNext is released, I will create a pre-release with this fix.

**Comment by matkoch** [comment]
@spikeyTheBest released here: https://resharper-plugins.jetbrains.com/packages/JetBrains.PresentationAssistant/2.8.1-pre0001
