### ISSUE TITLE
Presentation Assistant stopped working at some point

### ISSUE THREAD

**Issue by farzadmf** [JetBrains/resharper-presentation-assistant#28]
Hi,

First of all, thank you for this great add-on.

I'm not sure when it happened, but at some point, this add-on seems to have stopped working. I used to see the popup for the shortcuts, but now I don't see anything.

I checked in ReSharper's "Extension Manager..." setting, and the add-on seems to be properly installed.

Can you please tell me how I may be able to fix this?

Visual Studio version: 15.5.7
ReSharper version: 2017.3

**Comment by matkoch** [comment]
@farzadmf coincidentally I also just discovered that today. Will have a look later this week!

**Comment by farzadmf** [comment]
Thanks :)

**Comment by farzadmf** [comment]
Thank you @matkoch , it's working fine now 👍
