### ISSUE TITLE
Option to filter out some keystrokes from displaying

### ISSUE THREAD

**Issue by stecydube** [JetBrains/resharper-presentation-assistant#30]
Thank for making available your extension. Nice work!

Some action triggers multiple shortcuts, for example "Run Unit Tests Ctrl-U Ctrl-R" always seems to trigger "File Save All" and thus "Save All Ctrl-Shift S" is displayed instead of "Ctrl-U Ctrl-R".

Furthermore, after a while, some shortcuts I don't care to see anymore (Save All, Cut, Paste, etc...).

It would be nice to have a way to filter out some common shortcuts using an option panel.

**Comment by gutierlf** [comment]
Hi 👋. I too share my thanks for this great extension. I really like it. I also would appreciate the ability to show the commands, like test running, that get hidden when the Save All command appears instead. Thanks 🙏

**Comment by gutierlf** [comment]
Hmm, I just updated ReSharper and the Presentation Assistant, and I no longer get the test commands hidden by the Save All command 😃

**Comment by matkoch** [comment]
I also think this was addressed some time before.
