### ISSUE TITLE
Nothing Presented after Installing

### ISSUE THREAD

**Issue by jgyo** [JetBrains/resharper-presentation-assistant#8]
Is there something other than installing needed to make this work? I have installed within VS 2013 with R#9, but I never see any of the keys reported like you have shown for the plug-in.

What do I need to do?

**Comment by citizenmatt** [comment]
You need to enable it from the ReSharper → Tools menu. Select the "Presentation Assistant" menu option, and it'll be enabled. Any ideas on how to make this more obvious? Would it help to have a screenshot of the tools menu on the home page?

**Comment by jgyo** [comment]
A screen shot would help. I was able to find the option after a while, but it took a while. Because it was a R# plugin I looked for something within R# Options for it, and within the R# menu. I'm sure I looked on the Tools menu too, but overlooked it there.

Thanks for your note, and for the tool.

**Comment by brettjacobson** [comment]
I experienced the same issue!  Perhaps a screenshot or text describing how to enable the extension on the home page (that was the first place I looked for the information).

**Comment by citizenmatt** [comment]
I've updated the main README with an image of the Tools menu, so it should now be obvious what to do. Do you think that covers it?
